### PR TITLE
Adds a CRD and generated code for the ApplicationStatus resource

### PR DESCRIPTION
**Pull request by xamebax**
This PR introduces both a resource definition and generated client, informer etc. code for the Application Status resource. Thanks to having also this CRD we can easily build a watcher for this resource.

### CODE REVIEW

**Review by mortenlj — COMMENTED** [review]
Most of this is autogenerated I guess? 

The only thing I can see that makes me stop is the copyright header in some of the files. Should the copyright be assigned to us, or the Kubernetes Authors...?

**Review by oyvindio — APPROVED** [review]
The status types look good to me

**Comment by oyvindio** [comment]
> The only thing I can see that makes me stop is the copyright header in some of the files. Should the copyright be assigned to us, or the Kubernetes Authors...?

Maybe, unless there is any reason one can't claim copyright over generated code. In any case I think the file header of the generated code can be configured by modifying [`hack/boilerplate.go.txt`](https://github.com/fiaas/fiaas-go-client/blob/master/hack/boilerplate.go.txt)

**Comment by xamebax** [comment]
I actually haven't looked into that copyright before; I'll investigate.

**Comment by xamebax** [comment]
I updated the copyright headers. I think it should be fine now.

I also noticed that we're not adding the newly-generated `ApplicationStatus` type to the scheme in `register.go`, and I fixed that, too.

**Comment by tg90nor** [comment]
If Kubernetes authors wrote the code generator, then they probably have copyright to the generated code, and the header should probably reflect that.

**Comment by tg90nor** [comment]
Or another reasonable interpretation is that the generated code is not a creative work, and thus not copyrightable at all, but I would consult lawyers before taking this position.

**Comment by xamebax** [comment]
I don't think the copyright issue should block this CRD expansion from being merged. I suggest opening a separate issue for discussing the copyright part. Can this be merged as is? It's a blocker for removing Pipeline-specific code from FDD.

**Comment by xamebax** [comment]
Having said that, I reached out to Kubernetes maintainers on Slack in the meantime, and they confirmed the generated code doesn't have to have their copyright, and that it's also fine to add your own copyright header if necessary in the `boilerplate` text file.

**Pull request merged**
